#
# Host (use '0.0.0.0' to bind to all interfaces) and port
#
gateway.hostname = https://0.0.0.0:8080

#
# Configure credential and truststore
#

#
# gateway credential
#
gateway.credential.path=/local/server-credential.pem
gateway.credential.keyPath=/local/server-key.pem

#
# trusted certificates
#
gateway.truststore.type=directory
gateway.truststore.directoryLocations.1=/local/trusted/*.pem

#
# OAuth token generation support TBD
#
gateway.apitokens.enable=false
# gateway.apitokens.issuer=${OAUTH_ISSUER_URL}
# gateway.apitokens.clientID=${OAUTH_CLIENT_ID}
# gateway.apitokens.clientSecret=${OAUTH_CLIENT_SECRET}
# gateway.apitokens.scope=openid email profile

#
# Jetty server configuration
#
gateway.httpServer.requireClientAuthn=false
gateway.httpServer.minThreads=1
gateway.httpServer.maxThreads=255
# time after which an idle connection will be terminated
gateway.httpServer.maxIdleTime=30000

#
# dispatching options
#
gateway.client.chunked = true
gateway.client.socketTimeout = 1000000
gateway.client.connectionTimeout = 1000000
gateway.client.maxTotal=200
gateway.client.maxPerService=100
gateway.signConsignorToken = true

#
# disable dynamic registration.
# 
gateway.registration.enable=false
