
SERVERNAME="Gateway"

JAVA=${JAVA:-java}

#
# JVM memory settings
#
MEM="-Xmx256m"
MEM=$MEM" -XX:NativeMemoryTracking=summary"
MEM=$MEM" -XX:MaxMetaspaceSize=512M"


LIB="lib/"

CONF="conf"

PID="LAST_PID"

STARTLOG="/var/log/unicore/gateway-startup.log"

OPTS=$OPTS" -Dlog4j.configurationFile=$CONF/logging.properties"
