container.externalurl=${PUBLIC_ENDPOINT}
container.host=localhost
container.port=7777
container.sitename=UNICORE

container.security.credential.path=/local/server-credential.pem
container.security.credential.keyPath=/local/server-key.pem
container.security.credential.password=

container.security.truststore.type=directory
container.security.truststore.directoryLocations.1=/local/trusted/*.pem
container.security.truststore.ocspMode=IF_AVAILABLE

container.client.serverHostnameChecking=NONE
container.httpServer.maxIdleTime=30000
container.httpServer.maxThreads=255

persistence.directory=/var/run/unicore/

container.services.lifetime.default.JobManagement=2592000
container.services.lifetime.default.StorageManagement=2592000
container.services.lifetime.default=432000
container.services.registryEntryRefreshInterval=1800
