#
# Basic properties for UNICORE/X
#

SERVERNAME="UNICOREX"

JAVA=${JAVA:-java}

#
# Memory settings
#
MEM="-Xmx512m"
MEM=$MEM" -XX:NativeMemoryTracking=summary"
MEM=$MEM" -XX:MaxMetaspaceSize=1024M"

LIB="lib/"

CONF="conf"

PID="LAST_PID"

STARTLOG="/var/log/unicore/unicorex-startup.log"

#
# Main config file
#
MAIN_CONFIG="conf/main.config"

# Logging configuration file
OPTS=$OPTS" -Dlog4j.configurationFile=$CONF/logging.properties"
